name: temizlik_firmasi
description: Temizlik Firmasi İçin Geliştirilmiş Uygulama


publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.3.2
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^1.0.1
  flutter_icons: ^1.1.0
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
 
  uses-material-design: true

  assets:
    - assets/images/
 
